name: Test

permissions: {}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/**

jobs:
  test-publish-gem:
    name: It publishes a RubyGem in a folder
    runs-on: ubuntu-latest
    environment: Publish to Rubygems
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: 4.0.5
          bundler-cache: true
      - name: Configure RubyGems Credentials
        uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
      - name: Test the action
        uses: ./
        with:
          working-directory: "test"
      - name: Check latest published gem version is as expected
        run: |
          payload=$(curl https://rubygems.org//api/v1/versions/cucumber-test-release-automation/latest.json)
          actual_version=$(echo "$payload" | jq .version --raw-output)
          expected_version="0.0.${EXPECTED_PATCH_VERSION}"
          echo "actual_version: $actual_version"
          echo "expected_version: $expected_version"
          [ "${actual_version}" == "${expected_version}" ]
        env:
          EXPECTED_PATCH_VERSION: ${{ github.sha}}
